name: generate animation

on:
  # Run automatically every 24 hours
  schedule:
    - cron: "0 */24 * * *"
  
  # Allows to manually run the job at any time
  workflow_dispatch:
  
  # Run on every push to the master branch
  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Install 'canvas' dependencies and the 'canvas' module itself
      - name: Install canvas dependencies and npm
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev
          sudo apt-get install -y npm  # Install npm if it's not available
          npm install canvas  # Install the 'canvas' module

      # Step 2: Generate the contribution graph and animation (SVG and GIF)
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # Step 3: Push the content of <build_dir> to the 'output' branch
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
